-- Generated by tools/starcat/load_detail.py — edit that, not this.
--
-- Usage:
--   zstd -dc data/sky_star_detail.csv.zst \
--     | psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f tools/starcat/load_detail.sql
--
-- Input: two CSV columns, `id` ('g<gaia source_id>' | 'h<hip>') and a JSON
-- payload. The load is one transaction and a full replacement: a failure
-- leaves the table exactly as it was.

\set ON_ERROR_STOP on

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.sky_star_detail') IS NULL THEN
    RAISE EXCEPTION
      'sky_star_detail does not exist — run the drizzle migration first (pnpm db:migrate)';
  END IF;
END
$$;

CREATE TEMP TABLE sky_star_detail_incoming (
  id text NOT NULL,
  payload jsonb NOT NULL
) ON COMMIT DROP;

-- PSTDIN, not STDIN: inside a -f script psql reads STDIN from the script
-- file itself, so the piped data would never be seen.
\copy sky_star_detail_incoming (id, payload) FROM PSTDIN WITH (FORMAT csv)

-- A full replacement, not a merge: the build is the whole catalogue, so
-- TRUNCATE + INSERT is both simpler and far faster than an upsert plus an
-- anti-join delete over three million rows. It is inside the transaction, so
-- a failure anywhere leaves the old rows in place.
TRUNCATE sky_star_detail;

INSERT INTO sky_star_detail (id, payload, built_at)
SELECT id, payload, now() FROM sky_star_detail_incoming;

COMMIT;

SELECT count(*) AS sky_star_detail_rows FROM sky_star_detail;
