#!/usr/bin/env python3
r"""Load `data/sky_star_detail.csv.zst` into Postgres.

`psycopg` is not a dependency of this repo, so the loader emits a psql script
(`load_detail.sql`) and drives `psql` over a pipe: the compressed file is
decompressed on the fly and streamed straight into psql's `\copy ... FROM PSTDIN`,
so no 100 MB temp file is ever written.

    python3 tools/starcat/load_detail.py            # emit load_detail.sql only
    python3 tools/starcat/load_detail.py --run      # emit, then load

`--run` needs `DATABASE_URL` and `psql` on PATH. The table must already exist;
it is created by the drizzle migration for `sky_star_detail`, not here, and the
script fails loudly rather than loading into nothing:

    sky_star_detail(id text primary key,
                    payload jsonb not null,
                    built_at timestamptz not null)

Python 3 standard library only.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
DATA = Path(os.environ.get("RN_SKY_DATA", ROOT / "data"))
SQL_PATH = HERE / "load_detail.sql"

SQL = r"""-- Generated by tools/starcat/load_detail.py — edit that, not this.
--
-- Usage:
--   zstd -dc data/sky_star_detail.csv.zst \
--     | psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f tools/starcat/load_detail.sql
--
-- Input: two CSV columns, `id` ('g<gaia source_id>' | 'h<hip>') and a JSON
-- payload. The load is one transaction and a full replacement: a failure
-- leaves the table exactly as it was.

\set ON_ERROR_STOP on

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.sky_star_detail') IS NULL THEN
    RAISE EXCEPTION
      'sky_star_detail does not exist — run the drizzle migration first (pnpm db:migrate)';
  END IF;
END
$$;

CREATE TEMP TABLE sky_star_detail_incoming (
  id text NOT NULL,
  payload jsonb NOT NULL
) ON COMMIT DROP;

-- PSTDIN, not STDIN: inside a -f script psql reads STDIN from the script
-- file itself, so the piped data would never be seen.
\copy sky_star_detail_incoming (id, payload) FROM PSTDIN WITH (FORMAT csv)

-- A full replacement, not a merge: the build is the whole catalogue, so
-- TRUNCATE + INSERT is both simpler and far faster than an upsert plus an
-- anti-join delete over three million rows. It is inside the transaction, so
-- a failure anywhere leaves the old rows in place.
TRUNCATE sky_star_detail;

INSERT INTO sky_star_detail (id, payload, built_at)
SELECT id, payload, now() FROM sky_star_detail_incoming;

COMMIT;

SELECT count(*) AS sky_star_detail_rows FROM sky_star_detail;
"""


def detail_file() -> Path:
    for name in ("sky_star_detail.csv.zst", "sky_star_detail.csv.gz"):
        candidate = DATA / name
        if candidate.exists():
            return candidate
    sys.exit(f"no built detail file under {DATA} — run tools/starcat/build_detail.py first")


def decompressor(path: Path) -> list[str]:
    if path.suffix == ".zst":
        if not shutil.which("zstd"):
            sys.exit("zstd is not on PATH but the dataset is zstd-compressed")
        return ["zstd", "-dc", str(path)]
    return ["gzip", "-dc", str(path)]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", action="store_true", help="load into $DATABASE_URL")
    args = parser.parse_args()
    SQL_PATH.write_text(SQL, encoding="utf-8")
    print(f"wrote {SQL_PATH.relative_to(ROOT)}")
    if not args.run:
        source = detail_file()
        print("load with:\n  " + " ".join(decompressor(source))
              + f' | psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f {SQL_PATH.relative_to(ROOT)}')
        return

    url = os.environ.get("DATABASE_URL")
    if not url:
        sys.exit("DATABASE_URL is not set")
    if not shutil.which("psql"):
        sys.exit("psql is not on PATH")
    source = detail_file()
    print(f"loading {source.name} ({source.stat().st_size:,} bytes)")
    unpack = subprocess.Popen(decompressor(source), stdout=subprocess.PIPE)
    load = subprocess.Popen(
        ["psql", url, "-v", "ON_ERROR_STOP=1", "-f", str(SQL_PATH)],
        stdin=unpack.stdout)
    unpack.stdout.close()
    code = load.wait()
    unpack.wait()
    if code != 0:
        sys.exit(f"psql exited {code}")


if __name__ == "__main__":
    main()
