#!/usr/bin/env python3
"""Stamp every fetched sky asset with its own content hash, and say so in TS.

The sky is nine files and a manifest, and until this ran only two of them —
the Milky Way's two bakes — carried a hash in their name, and even those were
served `max-age=0`. Behind Cloudflare that means a `REVALIDATED` round trip to
the origin on every page load, once per asset, for files that had not changed
since the release before last. A content-addressed name is what lets them be
served `immutable` for a year instead: a rebuild writes a *different* URL, so
nothing anyone is holding is ever stale and no cache is ever purged.

The names are generated rather than typed. `assets.ts` reads them out of
`asset-names.ts`, which this writes; the bundle that imports it is already
content-hashed by Next, so the whole graph is immutable and the HTML is its
only mutable entry point.

Run last, after every builder that writes into `public/`:

    python3 tools/starcat/build_bright.py
    python3 tools/starcat/build_names.py
    python3 tools/starcat/build_lines.py
    python3 tools/starcat/build_star_lod.py --resort
    python3 tools/starcat/name_assets.py

It is idempotent: a file already carrying its own hash is left alone. Tiles are
not its business — `build_star_lod.py` names those from the sha256 its manifest
already records, because it is the thing that knows which bytes are a tile.

Python 3 standard library only.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PUBLIC = ROOT / "public"
MODULE = ROOT / "src" / "features" / "sky" / "asset-names.ts"
HASH_CHARS = 12

# key -> the URL path the builders write, before it is stamped. The order is
# the order the generated module lists them in.
ASSETS: dict[str, str] = {
    "bright": "/stars/bright.bin",
    "named": "/stars/named.json",
    "lines": "/sky/lines.bin",
    "milkyway": "/sky/milkyway.webp",
    "milkyway2k": "/sky/milkyway-2k.webp",
    "cities": "/cities/cities.bin",
    "earthDay": "/textures/earth/day.jpg",
    "earthNormal": "/textures/earth/normal.jpg",
    "earthSpecular": "/textures/earth/specular.jpg",
    "lodManifest": "/stars/lod/manifest.json",
}


def variants(directory: Path, stem: str, suffix: str) -> list[Path]:
    """Every file that is this asset: the bare name, and any hashed one.

    The pattern is anchored on a 12-hex tail so `milkyway-2k-<hash>.webp` is
    not read as a stamped `milkyway`, which a plain `milkyway-*` glob would do.
    """
    pattern = re.compile(rf"^{re.escape(stem)}(-[0-9a-f]{{{HASH_CHARS}}})?{re.escape(suffix)}$")
    return sorted(path for path in directory.iterdir() if pattern.match(path.name))


def current(url: str) -> Path:
    """Where this asset is on disk right now, stamped or not.

    Every builder reads and writes through this, because the file it wrote
    last time is not at the path it wrote it to any more. More than one match
    is a build that wrote a fresh output beside a stamped one: the bare name
    wins, because that is the fresh one; otherwise the newest.
    """
    target = PUBLIC / url.lstrip("/")
    found = variants(target.parent, target.stem, target.suffix)
    if not found:
        raise SystemExit(f"{url}: nothing under {target.parent}")
    for path in found:
        if path.name == target.name:
            return path
    return max(found, key=lambda path: path.stat().st_mtime)


def digest_of(url: str) -> str:
    """The 12-hex content hash of an asset as it is on disk now.

    `build_names.py` and `build_lines.py` write this into their own manifests:
    both address stars by *index* into `bright.bin`, and every record the
    catalogue gains moves the ones after it. Writing down which catalogue was
    resolved against turns "these three files were built together" from a
    thing a person has to remember into a thing a test can check.
    """
    return hashlib.sha256(current(url).read_bytes()).hexdigest()[:HASH_CHARS]


def stamp(url: str) -> str:
    """Rename this asset to carry its content hash; return the URL it now has."""
    target = PUBLIC / url.lstrip("/")
    stem, suffix = target.stem, target.suffix
    found = variants(target.parent, stem, suffix)
    source = current(url)
    digest = hashlib.sha256(source.read_bytes()).hexdigest()[:HASH_CHARS]
    stamped = target.parent / f"{stem}-{digest}{suffix}"
    if source != stamped:
        source.replace(stamped)
    for stale in found:
        if stale != stamped and stale.exists():
            stale.unlink()
    return url.rsplit("/", 1)[0] + "/" + stamped.name


def render(paths: dict[str, str]) -> str:
    entries = "\n".join(f"  {key}: '{path}'," for key, path in paths.items())
    return f"""/** Generated by `tools/starcat/name_assets.py` — do not edit.
 *
 * Every fetched sky asset, named by the sha256 of its own bytes. The names
 * change when the bytes do and never otherwise, which is what lets
 * `next.config.ts` serve all of them `immutable` for a year: a release cannot
 * invalidate a byte, and nothing is ever purged.
 */
export const SKY_ASSETS = {{
{entries}
}} as const;
"""


def main() -> None:
    paths = {key: stamp(url) for key, url in ASSETS.items()}
    MODULE.write_text(render(paths), encoding="utf-8")
    for key, path in paths.items():
        print(f"{key:14} {path}")
    print(f"wrote {MODULE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
