name: ronitnath

services:
  ronitnath:
    image: 127.0.0.1:5000/ronitnath/ronitnath:latest
    container_name: ronitnath
    restart: unless-stopped
    ports:
      - "18080:8080"
    environment:
      HOST: 0.0.0.0
      PORT: "8080"
      DATABASE_URL: sqlite:///app/data/ronitnath.db
    volumes:
      - ronitnath-data:/app/data
    pull_policy: always

volumes:
  ronitnath-data:
