/** Generated by `tools/starcat/name_assets.py` — do not edit.
 *
 * Every fetched sky asset, named by the sha256 of its own bytes. The names
 * change when the bytes do and never otherwise, which is what lets
 * `next.config.ts` serve all of them `immutable` for a year: a release cannot
 * invalidate a byte, and nothing is ever purged.
 */
export const SKY_ASSETS = {
  bright: '/stars/bright-567943e4c3f3.bin',
  named: '/stars/named-b9a17f938f50.json',
  lines: '/sky/lines-8a1a81fa0035.bin',
  milkyway: '/sky/milkyway-81ee6f522371.webp',
  milkyway2k: '/sky/milkyway-2k-cb776eaccca4.webp',
  cities: '/cities/cities-84730b566461.bin',
  earthDay: '/textures/earth/day-767ee1dc6eb3.jpg',
  earthNormal: '/textures/earth/normal-b594a277bf80.jpg',
  earthSpecular: '/textures/earth/specular-9b856deb4cf2.jpg',
  lodManifest: '/stars/lod/manifest-de73b89ef7c2.json',
} as const;
