/** The 88 constellations, abbreviation to name.
 *
 * The dataset carries both on every row already, but a row only knows its own
 * — and the abbreviation a star is *labelled* with does not always come from
 * the same place as the one the row computed. HYG v3 names a star's
 * constellation per star, curated; `build_detail.py` derives one by precessing
 * the position to B1875 and walking the IAU boundary arcs (VizieR VI/42). They
 * disagree on 13% of the stars HYG knows, and on every one this was checked
 * against — Rigil Kentaurus, Mimosa, Fomalhaut, Deneb Algedi — HYG is the one
 * that is right. So HYG wins where it has an answer, and this is the table
 * that turns its answer into a name (`star-detail.ts`).
 *
 * The pairs are exactly the ones the built dataset uses; HYG's own two
 * malformed codes (`Eco`, `Sir`) are absent, which is what makes the lookup
 * itself the test of whether HYG's answer is usable.
 */
export const CONSTELLATIONS: Readonly<Record<string, string>> = {
  And: 'Andromeda',
  Ant: 'Antlia',
  Aps: 'Apus',
  Aql: 'Aquila',
  Aqr: 'Aquarius',
  Ara: 'Ara',
  Ari: 'Aries',
  Aur: 'Auriga',
  Boo: 'Bootes',
  Cae: 'Caelum',
  Cam: 'Camelopardalis',
  Cap: 'Capricornus',
  Car: 'Carina',
  Cas: 'Cassiopeia',
  Cen: 'Centaurus',
  Cep: 'Cepheus',
  Cet: 'Cetus',
  Cha: 'Chamaeleon',
  Cir: 'Circinus',
  CMa: 'Canis Major',
  CMi: 'Canis Minor',
  Cnc: 'Cancer',
  Col: 'Columba',
  Com: 'Coma Berenices',
  CrA: 'Corona Australis',
  CrB: 'Corona Borealis',
  Crt: 'Crater',
  Cru: 'Crux',
  Crv: 'Corvus',
  CVn: 'Canes Venatici',
  Cyg: 'Cygnus',
  Del: 'Delphinus',
  Dor: 'Dorado',
  Dra: 'Draco',
  Equ: 'Equuleus',
  Eri: 'Eridanus',
  For: 'Fornax',
  Gem: 'Gemini',
  Gru: 'Grus',
  Her: 'Hercules',
  Hor: 'Horologium',
  Hya: 'Hydra',
  Hyi: 'Hydrus',
  Ind: 'Indus',
  Lac: 'Lacerta',
  Leo: 'Leo',
  Lep: 'Lepus',
  Lib: 'Libra',
  LMi: 'Leo Minor',
  Lup: 'Lupus',
  Lyn: 'Lynx',
  Lyr: 'Lyra',
  Men: 'Mensa',
  Mic: 'Microscopium',
  Mon: 'Monoceros',
  Mus: 'Musca',
  Nor: 'Norma',
  Oct: 'Octans',
  Oph: 'Ophiuchus',
  Ori: 'Orion',
  Pav: 'Pavo',
  Peg: 'Pegasus',
  Per: 'Perseus',
  Phe: 'Phoenix',
  Pic: 'Pictor',
  PsA: 'Piscis Austrinus',
  Psc: 'Pisces',
  Pup: 'Puppis',
  Pyx: 'Pyxis',
  Ret: 'Reticulum',
  Scl: 'Sculptor',
  Sco: 'Scorpius',
  Sct: 'Scutum',
  Ser: 'Serpens',
  Sex: 'Sextans',
  Sge: 'Sagitta',
  Sgr: 'Sagittarius',
  Tau: 'Taurus',
  Tel: 'Telescopium',
  TrA: 'Triangulum Australe',
  Tri: 'Triangulum',
  Tuc: 'Tucana',
  UMa: 'Ursa Major',
  UMi: 'Ursa Minor',
  Vel: 'Vela',
  Vir: 'Virgo',
  Vol: 'Volans',
  Vul: 'Vulpecula',
};
