import{createHash}from'node:crypto';import{Pool}from'pg';
import{config as loadEnv}from'dotenv';loadEnv({path:['.env.local','.env'],quiet:true});
import{LEDGER_MIGRATIONS,createAccount,createBook,createUnit,grantBookAccess,openPeriod,registerApplicationPrincipal}from'@isoastra/fleet-ledger';
import{ACCOUNTING_MIGRATION}from'@isoastra/fleet-accounting';import{ACCOUNTING_V2_MIGRATION}from'@isoastra/fleet-accounting/advanced';
import{BILLING_ACCOUNTING_MIGRATION}from'@isoastra/fleet-billing/accounting';import{SUBSCRIPTION_MIGRATION}from'@isoastra/fleet-billing/subscriptions';
const connectionString=process.env.DATABASE_URL;if(!connectionString)throw new Error('DATABASE_URL is not set');const pool=new Pool({connectionString,max:1});
const migrations=[...LEDGER_MIGRATIONS,{id:'0003-accounting',sql:ACCOUNTING_MIGRATION},{id:'0004-accounting-workflows',sql:ACCOUNTING_V2_MIGRATION},{id:'0005-billing-accounting',sql:BILLING_ACCOUNTING_MIGRATION},{id:'0006-subscriptions',sql:SUBSCRIPTION_MIGRATION}];
async function migrate(){await pool.query('CREATE TABLE IF NOT EXISTS app_package_migration(id text PRIMARY KEY,checksum text NOT NULL,applied_at timestamptz NOT NULL DEFAULT clock_timestamp())');for(const migration of migrations){const checksum=createHash('sha256').update(migration.sql).digest('hex'),found=await pool.query<{checksum:string}>('SELECT checksum FROM app_package_migration WHERE id=$1',[migration.id]);if(found.rows[0]){if(found.rows[0].checksum!==checksum)throw new Error(`package migration checksum drift: ${migration.id}`);continue}const client=await pool.connect();try{await client.query('BEGIN');await client.query(migration.sql);await client.query('INSERT INTO app_package_migration(id,checksum) VALUES($1,$2)',[migration.id,checksum]);await client.query('COMMIT')}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}console.log(`billing migrations: ${migrations.length} current`)}
async function seed(){await createUnit(pool,{code:'USD',scale:2});const role=String((await pool.query<{current_user:string}>('SELECT current_user')).rows[0]!.current_user),applicationId='ronitnath.com';const principal=await pool.query('SELECT 1 FROM fleet_ledger_application_principal WHERE db_role=$1',[role]);if(!principal.rowCount)await registerApplicationPrincipal(pool,{dbRole:role,applicationId});for(const seller of [{id:'ronit',name:'Ronit Nath',book:'ronitnath-usd'},{id:'isoastra',name:'Isoastra',book:'isoastra-usd'}]){await createBook(pool,{id:seller.book,entityId:seller.id,reportingUnit:'USD'});await openPeriod(pool,seller.book,'2020-01-01','2100-01-01');await grantBookAccess(pool,{applicationId,bookId:seller.book,capabilities:['read','post','administer','close']});const chart:Record<string,string>={};for(const name of ['receivable','deferredRevenue','revenue','processorClearing','cash','feeExpense','contraRevenue','refundLiability','customerCredit']){const id=`${seller.book}:${name}`;try{await createAccount(pool,{id,bookId:seller.book,name,unit:'USD',minimumAtoms:null,maximumAtoms:null})}catch(error){if((error as{code?:string}).code!=='23505')throw error}chart[name]=id}await pool.query('INSERT INTO billing_seller(id,name,book_id,chart,enabled) VALUES($1,$2,$3,$4::jsonb,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,book_id=EXCLUDED.book_id,chart=EXCLUDED.chart',[seller.id,seller.name,seller.book,JSON.stringify(chart)])}console.log('billing sellers: explicit Ronit and Isoastra mappings initialized disabled')}
async function main(){try{if(process.argv[2]==='migrate')await migrate();else if(process.argv[2]==='seed')await seed();else throw new Error('expected migrate or seed')}finally{await pool.end()}}
main().catch((error:unknown)=>{console.error(error instanceof Error?error.message:error);process.exit(1)});
